### ISSUE TITLE
Examples in docs or ReadMe?

### ISSUE THREAD

**Issue by briochemc** [SciML/SciMLStructures.jl#23]
Should the documentation or the ReadMe (or both) contain some examples of how to use SciMLStructures? I'm there must be some examples out there, but don't know where they are (and the tests here don't have any examples either).

**Comment by ChrisRackauckas** [comment]
There aren't quite enough examples out there to document right now. This interface is still gaining traction around the rest of the ecosystem and so I don't think it's quite ready for that yet.

**Comment by moble** [comment]
I got an error when trying to use Zygote (via DifferentiationInterface) to take the gradient of a cost function involving an ODE.  I understand why, but for lack of docs I have no idea how to wrap my parameters — which is just a named tuple that's constant WRT the differentiation variable.  (I'll just use ForwardDiff for now.)  But since that's one of the well advertised use cases for SciML, maybe that could be demonstrated?

**Comment by ChrisRackauckas** [comment]
That should now be working with today's release. I think we're almost ready to have this be a standard.

@AayushSabharwal could you cook up an example of a SciMLStructure to document the interface?
